services:
  bot:
    build: ./app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./app:/app
    networks:
      - nedaai-mongo-net
    depends_on:
      - nedaai-mongo

  nedaai-mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - nedaai-mongo-net

networks:
  nedaai-mongo-net:
    name: nedaai-mongo-net
