services:
  bot:
    build: ./app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./app:/app
    networks:
      - nedaai-mongo-net
    depends_on:
      - nedaai-mongo

  nedaai-mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - db:/data/db
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - nedaai-mongo-net

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_SERVER=nedaai-mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=your_password_here
    ports:
      - "8082:8081"
    networks:
      - nedaai-mongo-net
    depends_on:
      - nedaai-mongo

networks:
  nedaai-mongo-net:
    name: nedaai-mongo-net

volumes:
  db:
