services:
  bot:
    build: ./app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./app:/app
    networks:
      - nedaai-mongo-net
    depends_on:
      - nedaai-mongo

  nedaai-mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - ./:
      - "127.0.0.1:27017:27017"
    networks:
      - nedaai-mongo-net
    # no authentication — open access for internal services only

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_SERVER=nedaai-mongo
      - ME_CONFIG_MONGODB_URL=mongodb://nedaai-mongo:27017/
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD= # empty because your mongo has no password
      - ME_CONFIG_BASICAUTH_USERNAME=admin # mongo-express login user
      - ME_CONFIG_BASICAUTH_PASSWORD=your_password_here # mongo-express login pass
    ports:
      - "8081:8081"
    networks:
      - nedaai-mongo-net
    depends_on:
      - nedaai-mongo

networks:
  nedaai-mongo-net:
    name: nedaai-mongo-net
